### ISSUE TITLE
点登陆启动 会出现两个快捷图标

### ISSUE THREAD

**Issue by swuecho** [DargonLee/easy_pasta#1]
<img width="479" alt="image" src="https://github.com/DargonLee/easy_pasta/assets/666683/c1eee4d7-7c41-46b9-9bd6-07094e146d3b">

**Comment by DargonLee** [comment]
已记录，稍后修复。

**Comment by DargonLee** [comment]
已确认是 bug，稍后修复。

**Comment by DargonLee** [comment]
已修复，下个版本发布。
